version: '3.8'

services:
  # Backend API service
  backend:
    build: ./backend
    container_name: transkiptor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /tmp/transkiptor:/tmp/transkiptor  # For temporary files
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - transkiptor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend web service
  frontend:
    build: ./frontend
    container_name: transkiptor-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - transkiptor-network

volumes:
  transkiptor_data:

networks:
  transkiptor-network:
    driver: bridge